AWSTemplateFormatVersion: 2010-09-09

Transform: AWS::Serverless-2016-10-31

Description: Schedy Hermes Api

Parameters:

  Environment:
    Type: String
    Description: Set the deployment environment.
    AllowedValues:
      - Development
      - Staging
      - Production

  JwtSecret:
    Type: String
    Description: Set secret token JWT

Mappings:
  StageNameMap:
    Development:
      StageName: dev
    Staging:
      StageName: stg
    Production:
      StageName: prod
  EnvironmentToPathBaseMap:
    Development:
      PathBase: /development
    Staging:
      PathBase: /staging
    Production:
      PathBase: /

Globals:
  Api:
    OpenApiVersion: 3.0.1

Resources:
  Lambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: schedy-hermes-api
      Handler: Schedy.Hermes.Api::Schedy.Hermes.Api.LambdaEntryPoint::FunctionHandlerAsync
      Runtime: dotnet6
      MemorySize: 1024
      Timeout: 30
      Environment:
        Variables:
          ASPNETCORE_ENVIRONMENT: !Ref Environment
          ASPNETCORE_JWT__Secret: !Ref JwtSecret
          ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS: true
          ASPNETCORE_PATH_BASE: !FindInMap [EnvironmentToPathBaseMap, !Ref Environment, PathBase]
          ASPNETCORE_Logging__IncludeLogLevel: true
          ASPNETCORE_Logging__IncludeCategory: true
          ASPNETCORE_Logging__IncludeNewline: true
          ASPNETCORE_Logging__IncludeException: true
          ASPNETCORE_Logging__IncludeEventId: false
          ASPNETCORE_Logging__IncludeScopes: false
          ASPNETCORE_Logging__LogLevel__Default: Information
          ASPNETCORE_Logging__LogLevel__Microsoft: Warning
          ASPNETCORE_Logging__LogLevel__System: Warning
      Events:
        AnyHttpRequest:
          Type: Api
          Properties:
            Path: "/{proxy+}"
            Method: ANY
            RestApiId: !Ref ApiGateway
      Role: !Sub arn:aws:iam::${AWS::AccountId}:role/AppLambdaExecutionRole
      Tags:
        Name: schedy-hermes-api:Lambda

  ApiGateway:
    Type: AWS::Serverless::Api

    Properties:
      StageName: !FindInMap [StageNameMap, !Ref Environment, StageName]
      Name: schedy-hermes-api
      Tags:
        Name: schedy-hermes-api:ApiGateway
